# Generated by Django 3.2 on 2021-04-20 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=127, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('city_name', models.CharField(default='', max_length=150)),
                ('address', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=150, null=True)),
                ('website', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=150, null=True)),
                ('fax_number', models.CharField(max_length=150, null=True)),
                ('firm_rankings', models.ManyToManyField(related_name='firm_rankings', to='outreach.Ranking')),
                ('top_tier_firm_rankings', models.ManyToManyField(related_name='top_tier_firm_rankings', to='outreach.Ranking')),
            ],
        ),
        migrations.CreateModel(
            name='Attorney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=127, unique=True)),
                ('email', models.CharField(max_length=127, null=True)),
                ('phone_number', models.CharField(max_length=127, null=True)),
                ('picture', models.CharField(max_length=200)),
                ('firm_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outreach.firm')),
            ],
        ),
    ]
